<a href="https://colab.research.google.com/github/steviet108/ML-Tech-Startups/blob/main/GC_venture_funding_with_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
# Here we are importing all the dependencies and packages. There are a few new packages to note, specifically the tensorflow modules. We are going
# to be building neural networks so we use the Dense function and the Suquential function, both part of the tensorflow module.
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from pathlib import Path

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Upload credit_card_transactions.csv to Colab
# Here is some slick code to upload csv files into Google Colab.
from google.colab import files

csv_file = files.upload()

Saving applicants_data.csv to applicants_data (6).csv

In [3]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
# Here we are having the pandas read_csv() function read in the csv file and create dataframe with it. We pass the name of the csv file as an argument.
applicant_data_df = pd.read_csv(Path('applicants_data.csv'))

# Review the DataFrame
# Here we call the name of the dataframe we just created to review and see what the data is in the dataframe.
applicant_data_df

             EIN  ... IS_SUCCESSFUL
0       10520599  ...             1
1       10531628  ...             1
2       10547893  ...             0
3       10553066  ...             1
4       10556103  ...             1
...          ...  ...           ...
34294  996009318  ...             0
34295  996010315  ...             0
34296  996012607  ...             0
34297  996015768  ...             1
34298  996086871  ...             0

[34299 rows x 12 columns]

In [4]:
# Review the data types associated with the columns
# Here we can use the dtypes function to see what kind of data we have in our dataframe. This is very useful to see because we are building a Neural Network later
# and its going to benefit us and the accuracy of the NN to change the 'objects' into integers. Thats becasue the algorithims cannot make sense of different categorical
# labels. We will assign the categories an integer.
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [5]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
# Here we drop the 'EIN' and 'NAME' columns becasue they really serve us no purpose in the neural network model. In fact the 'EIN' could break the model, and the 
# 'Name' is useless as well as being categorical. So we just drop them useing the .drop() function.
applicant_data_df = applicant_data_df.drop(columns=['EIN', 'NAME'])

# Review the DataFrame
# Here we can review the dataframe to see if indeed we dropped the two columns.
applicant_data_df

      APPLICATION_TYPE       AFFILIATION  ...   ASK_AMT IS_SUCCESSFUL
0                  T10       Independent  ...      5000             1
1                   T3       Independent  ...    108590             1
2                   T5  CompanySponsored  ...      5000             0
3                   T3  CompanySponsored  ...      6692             1
4                   T3       Independent  ...    142590             1
...                ...               ...  ...       ...           ...
34294               T4       Independent  ...      5000             0
34295               T4  CompanySponsored  ...      5000             0
34296               T3  CompanySponsored  ...      5000             0
34297               T5       Independent  ...      5000             1
34298               T3       Independent  ...  36500179             0

[34299 rows x 10 columns]

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [6]:
# Create a list of categorical variables 
# Here we are making a list of all the categorical columns. These categories can break the model unless we modify them into integers.
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

# Display the categorical variables list
# A simple display() command to view our list.
display(categorical_variables)

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [7]:
# Create a OneHotEncoder instance
# Here we are going to use OneHotEncoder to cfonvert all the categories into a number value. Basically what happens is the sklearn.preprocessing module
# is able to give these categorical labels a number value either 1 or 0, and depending on how many cateories there is, relates to how many new columns 
# are created. So for example if there was previously 4 'Organization' categories, OneHotEncoder would create 4 new columns in the dataframe and give each row
# one value depending on their category.. Here we create the OneHotEncoder instance and give it a new name = enc.
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(sparse=False)

In [8]:
# Encode the categorcal variables using OneHotEncoder
# Here we use the .fit_transform() function and pass it the categorical_variables columns from the dataframe.
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [9]:
# Create a DataFrame with the encoded variables
# Here we are creating a new dataframe that will include the new columns the OneHotEncoder created earlier, so were previously we had 10 columns, now 
# we have 114 columns. To do this we are using pandas DataFrame() function as well as sklearn.preprocessing .get_feature_names_out() function.
encoded_df = pd.DataFrame(encoded_data, columns = enc.get_feature_names_out(categorical_variables))


# Review the DataFrame
# And here we call on the dataframe to review it.
encoded_df

       APPLICATION_TYPE_T10  ...  SPECIAL_CONSIDERATIONS_Y
0                       1.0  ...                       0.0
1                       0.0  ...                       0.0
2                       0.0  ...                       0.0
3                       0.0  ...                       0.0
4                       0.0  ...                       0.0
...                     ...  ...                       ...
34294                   0.0  ...                       0.0
34295                   0.0  ...                       0.0
34296                   0.0  ...                       0.0
34297                   0.0  ...                       0.0
34298                   0.0  ...                       0.0

[34299 rows x 114 columns]

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [10]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
# Here we use the pd.concat() function to join the two dataframes, encoded_df and the applicant_data_df dataframes. I only wanted to include the 
# the numerical variables from the original dataframe called applicants_data_df, because the categorical columns have already been included into a new
# dataframe called encoded_df. So when I concat, I call the applicants_data_df dataframe but only include the columns I want to include so we don't
# double up on the data, or use the same data twice.

encoded_df = pd.concat([encoded_df, applicant_data_df[['STATUS', 'ASK_AMT', 'IS_SUCCESSFUL']]], axis=1)

# Review the Dataframe
encoded_df

       APPLICATION_TYPE_T10  APPLICATION_TYPE_T12  ...   ASK_AMT  IS_SUCCESSFUL
0                       1.0                   0.0  ...      5000              1
1                       0.0                   0.0  ...    108590              1
2                       0.0                   0.0  ...      5000              0
3                       0.0                   0.0  ...      6692              1
4                       0.0                   0.0  ...    142590              1
...                     ...                   ...  ...       ...            ...
34294                   0.0                   0.0  ...      5000              0
34295                   0.0                   0.0  ...      5000              0
34296                   0.0                   0.0  ...      5000              0
34297                   0.0                   0.0  ...      5000              1
34298                   0.0                   0.0  ...  36500179              0

[34299 rows x 117 columns]

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [13]:
# Define the target set y using the IS_SUCCESSFUL column
# Here we are taking the colume 'IS_SUCCESSFUL' from the dataframe and setting it to y, for the NN model we are getting ready to create. This 
# column will be aour target column, or the column that we are trying to predict with the model we will build.
y = encoded_df['IS_SUCCESSFUL']

# Display a sample of y
# And here is a quick display to see what y looks like. We just call the first 5 rows.
y

0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

In [14]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
# Here we want all the columns except 'IS_SUCCESSFUL', so we use the drop() and pass it the column we want to drop. These columns will make up the features
# in our test and train dataset for the prediction model that we will build. We assign this dataset to X. Basically this is the dataset that the NN
# model will use to make predictions.
X = encoded_df.drop(columns=['IS_SUCCESSFUL'])

# Review the features DataFrame
# Here we review what X will look like. Note, it does not include the 'IS_SUCCESSFUL' column.
X[:5]

   APPLICATION_TYPE_T10  APPLICATION_TYPE_T12  ...  STATUS  ASK_AMT
0                   1.0                   0.0  ...       1     5000
1                   0.0                   0.0  ...       1   108590
2                   0.0                   0.0  ...       1     5000
3                   0.0                   0.0  ...       1     6692
4                   0.0                   0.0  ...       1   142590

[5 rows x 116 columns]

### Step 6: Split the features and target sets into training and testing datasets.

In [15]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
# Here we use the train_test_split() function from sklearn.model_selection. This function assigns some data to the training component of the 
# model and reserves some for the test component of the model. Random_state=1 has to do with how the function selects randomly from the data to assign it
# to either test or train.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [16]:
# Create a StandardScaler instance
# Here we are using the StandardScaler() function to scale all the numerical values in the dataset. The purpose is so that all the valuse are scaled, 
# specifically the 'ASK_AMOUNT' column will now be scaled to the rest of the data and that column wont screw up the model. This is very important for
# a robust accurate model. So we create a instance for the StandardScaler and assign it to the variable scaler.
scaler = StandardScaler()

# Fit the scaler to the features training dataset
# And here we pass the scaler instance to the fit() function with X_train dataset as the argument.
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
# Here we use the transform() function and pass it to X_scaler with the relevant datasets. Now we have scaled datasets to use in our model.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [17]:
# Define the the number of inputs (features) to the model
# Here we are using the len() function and passing the X_train dataset , row 0 as the argument, to see how many columns we can assign to number_input_features.
number_input_features = len(X_train.iloc[0])

# Review the number of features
# Here we review the number_input_features and see it has 116 rows, wich adds up becasue after the OneHotEncoding we had 117 less 1 column for the target.
number_input_features

116

In [26]:
# Define the number of neurons in the output layer
# Here we are defining the number of neurons in the output layer of the model. We use 1, becasue there is always just 1 output layer in a NN. It is
# responsible for producing the final output, and takes in  the inputs which are passed in from the layers before it, performs the calculations via
# its neurons and then the output is computed.
number_output_neurons = 1

In [19]:
# Define the number of hidden nodes for the first hidden layer
# Here we are defining the number of hidden nodes in the first hidden layer, its common practice to basically use half the number of input_features 
# for the first hidden layer. So we add the input_features and ouput and divide by 2 to get the number of nodes in the first hidden layer of our model.
hidden_nodes_layer1 =  (number_input_features + 1) // 2

# Review the number hidden nodes in the first layer
# Here we review how many nodes in the first hidden layer
hidden_nodes_layer1

58

In [20]:
# Define the number of hidden nodes for the second hidden layer
# The nodes for the second hidden layer should be around half the nodes for the first hidden layer, so we do a similiar equation to find that number.
hidden_nodes_layer2 =  (hidden_nodes_layer1 + 1) // 2

# Review the number hidden nodes in the second layer
# Here we review how many nodes in the second hidden layer
hidden_nodes_layer2

29

In [21]:
# Create the Sequential model instance
# Here we create an instance for the Sequential model and assign it to the variable nn.
nn = Sequential()

In [22]:
# Add the first hidden layer
# Here we use the add() function to add the first hidden layer to nn, and define some of the parameters, specifically, how many units, input_dimension
# and the activation function. We have chosen to use the rectified linear unit (ReLU) function (Links to an external site.). It is currently the world's 
# most-used activation function when it comes to training deep neural networks.
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

In [24]:
# Add the second hidden layer
# Here we use the add() function to add the second hidden layer to nn, and define some of the parameters, specifically, how many units
# and the activation function. We have chosen to use the rectified linear unit (ReLU) function (Links to an external site.). It is currently the world's 
# most-used activation function when it comes to training deep neural networks. 
nn.add(Dense(units=hidden_nodes_layer2, activation='relu'))

In [27]:
# Add the output layer to the model specifying the number of output neurons and activation function
# Here we use the .add() function to add the parameters of the output layer to the nn model. Now, for
# our classification model’s output layer, we use the sigmoid activation function. The sigmoid function
# will transform the output to a range between 0 and 1. 
nn.add(Dense(units=number_output_neurons, activation='sigmoid'))

In [28]:
# Display the Sequential model summary
# Here we use the summary() function to display the structure of the model, the output shape and number of
# weights—of each layer in our neuron model.
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 58)                6786

 dense_1 (Dense)             (None, 29)                1711

 dense_2 (Dense)             (None, 29)                870

 dense_3 (Dense)             (None, 1)                 30

=================================================================
Total params: 9,397
Trainable params: 9,397
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [29]:
# Compile the Sequential model
# Here we compile the model by using the compile() function provided by keras, and pass several parameters. Where previously we designed the model
# and defined the parameters, here with the compile() function we are actually going to construct the model. We include loss, optimizer and metrics 
# as parameters. The loss function uses machine learning algorithms to score the performance of the model after each of these iterations. This allows
# us to see how the model’s performance changes over each iteration. We also use the optimizer function, this function shapes and molds a neural
# network model while the model is trained on the data, to ensure that the model performs to the best of its ability. At a glance, an optimization 
# function reduces the model’s losses and provides the most accurate output possible. The metrics parameter specifies additional metrics that assess 
# the quality of a neural network model.
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [30]:
# Fit the model using 50 epochs and the training data
# Here we use the .fit() function to train the nn model to X_train_scaled dataset and y_train dataset, also we set the amount of epochs to 50.
# An epoch is a single pass of the entire training dataset through the model.
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5732 - accuracy: 0.7205
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5522 - accuracy: 0.7295
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5490 - accuracy: 0.7302
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5467 - accuracy: 0.7311
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7338
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7336
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5433 - accuracy: 0.7346
Epoch 8/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5426 - accuracy: 0.7343
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7353
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7364
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7369
Epoch 12/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5405 - accuracy: 0.7363
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7369
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7364
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7367
Epoch 16/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5389 - accuracy: 0.7373
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7374
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7372
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7385
Epoch 20/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5374 - accuracy: 0.7387
Epoch 21/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5373 - accuracy: 0.7384
Epoch 22/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5372 - accuracy: 0.7382
Epoch 23/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5364 - accuracy: 0.7391
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7372
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7383
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7392
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7387
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7393
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7397
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7403
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7391
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7398
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7393
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7397
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7401
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7402
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7403
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7409
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7406
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7401
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7401
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7414
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7405
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7409
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7398
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7409
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7400
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7404
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7408
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7410

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [50]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
# Now we can evaluate the model by using the .evaluate() function. This function shows the performance of the model.
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
# Display the model loss and accuracy results
# Here we use a print command to print a f' string 
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5569 - accuracy: 0.7294 - 426ms/epoch - 2ms/step
Loss: 0.5569039583206177, Accuracy: 0.7294460535049438

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [32]:
# Set the model's file path
# Here we name the model AlphabetSoup.h5 and give it the variable name file_path.
file_path = 'AlphabetSoup.h5'

# Export your model to a HDF5 file
# Here we use the save() function to save the model to the file path name we preciously determined. This way we can pass the model to a freind or
# colleague.
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [33]:
# Define the the number of inputs (features) to the model
# Here we are using the len() function and passing the X_train dataset , row 0 as the argument, to see how many columns we can assign to number_input_features.
number_input_features = len(X_train.iloc[0])

# Review the number of features
# We review the number of input features by calling the variable.
number_input_features

116

In [34]:
# Define the number of neurons in the output layer
# Here we are defining the number of neurons in the output layer of the model. We use 1, becasue there is always just 1 output layer in a NN. It is
# responsible for producing the final output, and takes in  the inputs which are passed in from the layers before it, performs the calculations via
# its neurons and then the output is computed.
number_output_neurons_A1 = 1

In [37]:
# Define the number of hidden nodes for the first hidden layer
# Here we are defining the number of hidden nodes in the first hidden layer, its common practice to basically use half the number of input_features 
# for the first hidden layer. So we add the input_features and ouput and divide by 2 to get the number of nodes in the first hidden layer of our model.
hidden_nodes_layer1_A1 = 58

# Review the number of hidden nodes in the first layer
# Here we review the number of hidden nodes in layer A1.
hidden_nodes_layer1_A1

58

In [36]:
# Create the Sequential model instance
# Here we create an instance for the Sequential model and assign it to the variable nn_A1.
nn_A1 = Sequential()

In [38]:
# First hidden layer
# Here we use the add() function to add the first hidden layer to nn, and define some of the parameters, specifically, how many units, input_dimension
# and the activation function. We have chosen to use the rectified linear unit (ReLU) function (Links to an external site.). It is currently the world's 
# most-used activation function when it comes to training deep neural networks.
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation='relu'))


# Output layer
# Here we use the .add() function to add the parameters of the output layer to the nn model. Now, for
# our classification model’s output layer, we use the sigmoid activation function. The sigmoid function
# will transform the output to a range between 0 and 1. 
nn_A1.add(Dense(units=1, activation='sigmoid'))


# Check the structure of the model
# Here we use the summary() function to look at the structure of our model.
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 58)                6786

 dense_5 (Dense)             (None, 1)                 59

=================================================================
Total params: 6,845
Trainable params: 6,845
Non-trainable params: 0
_________________________________________________________________

In [39]:
# Compile the Sequential model
# Here we compile the model by using the compile() function provided by keras, and pass several parameters. Where previously we designed the model
# and defined the parameters, here with the compile() function we are actually going to construct the model. We include loss, optimizer and metrics 
# as parameters. The loss function uses machine learning algorithms to score the performance of the model after each of these iterations. This allows
# us to see how the model’s performance changes over each iteration. We also use the optimizer function, this function shapes and molds a neural
# network model while the model is trained on the data, to ensure that the model performs to the best of its ability. At a glance, an optimization 
# function reduces the model’s losses and provides the most accurate output possible. The metrics parameter specifies additional metrics that assess 
# the quality of a neural network model. In this second model we have used the 'categorical_crossentropy' function to try and increase the performance
# of the model. Categorical_crossentropy is used when OneHotEncoder has been used. I though it might increase the performance so I wanted to try.
nn_A1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [59]:
# Fit the model using 50 epochs and the training data
# Here we use the .fit() function to train the nn model to X_train_scaled dataset and y_train dataset, also we set the amount of epochs to 50.
# An epoch is a single pass of the entire training dataset through the model.
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 3/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 4/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 5/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 6/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 10/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 13/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 14/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 15/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 22/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 23/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 25/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 27/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 29/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 33/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 35/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 36/50
804/804 [==============================] - 2s 3ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 37/50
804/804 [==============================] - 2s 3ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 38/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 39/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 40/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 44/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 45/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 46/50
804/804 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4665

#### Alternative Model 2

In [41]:
# Define the the number of inputs (features) to the model
# Here we are using the len() function and passing the X_train dataset , row 0 as the argument, to see how many columns we can assign to number_input_features.
number_input_features = len(X_train.iloc[0])

# Review the number of features
# Here we review the number of input features.
number_input_features

116

In [44]:
# Define the number of neurons in the output layer
# Here we are defining the number of neurons in the output layer of the model. We use 1, becasue there is always just 1 output layer in a NN. It is
# responsible for producing the final output, and takes in  the inputs which are passed in from the layers before it, performs the calculations via
# its neurons and then the output is computed.
number_output_neurons_A2 = 1
number_output_neurons_A2

1

In [56]:
# Define the number of hidden nodes for the first hidden layer
# Here we are defining the number of hidden nodes in the first hidden layer, its common practice to basically use half the number of input_features 
# for the first hidden layer. So we add the input_features and ouput and divide by 2 to get the number of nodes in the first hidden layer of our model.
hidden_nodes_layer1_A2 = 58

# Review the number of hidden nodes in the first layer
# Here a review of the number of hidden ndes in layer 1_A2.
hidden_nodes_layer1_A2

58

In [46]:
# Create the Sequential model instance
# Here we create an instance for the Sequential model and assign it to the variable nn_A2.
nn_A2 = Sequential()

In [47]:
# First hidden layer
# Here we use the add() function to add the first hidden layer to nn, and define some of the parameters, specifically, how many units, input_dimension
# and the activation function. We have chosen to use the rectified linear unit (ReLU) function (Links to an external site.). It is currently the world's 
# most-used activation function when it comes to training deep neural networks.
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation='relu'))

# Output layer
# Here we use the .add() function to add the parameters of the output layer to the nn model. Now, for
# our classification model’s output layer, we use the sigmoid activation function. The sigmoid function
# will transform the output to a range between 0 and 1. 
nn_A2.add(Dense(units=1, activation='sigmoid'))

# Check the structure of the model.
# Review the structure of model nn_A2.
nn_A2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 108)               12636

 dense_7 (Dense)             (None, 1)                 109

=================================================================
Total params: 12,745
Trainable params: 12,745
Non-trainable params: 0
_________________________________________________________________

In [48]:
# Compile the model
# Here we compile the model by using the compile() function provided by keras, and pass several parameters. Where previously we designed the model
# and defined the parameters, here with the compile() function we are actually going to construct the model. We include loss, optimizer and metrics 
# as parameters. The loss function uses machine learning algorithms to score the performance of the model after each of these iterations. This allows
# us to see how the model’s performance changes over each iteration. We also use the optimizer function, this function shapes and molds a neural
# network model while the model is trained on the data, to ensure that the model performs to the best of its ability. At a glance, an optimization 
# function reduces the model’s losses and provides the most accurate output possible. The metrics parameter specifies additional metrics that assess 
# the quality of a neural network model. In this model I went back to 'binary_crossentropy' to see if I could increase the performance.
nn_A2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [57]:
# Fit the model
# Here we use the .fit() function to train the nn model to X_train_scaled dataset and y_train dataset, also we set the amount of epochs to 75.
# An epoch is a single pass of the entire training dataset through the model.
nn_A2.fit(X_train_scaled, y_train, epochs=75)

Epoch 1/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7392
Epoch 2/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7375
Epoch 3/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7398
Epoch 4/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7393
Epoch 5/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7386
Epoch 6/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7390
Epoch 7/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7388
Epoch 8/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7393
Epoch 9/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7395
Epoch 10/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7392
Epoch 11/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7399
Epoch 12/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7387
Epoch 13/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7391
Epoch 14/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7396
Epoch 15/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7385
Epoch 16/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7391
Epoch 17/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7401
Epoch 18/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7400
Epoch 19/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7403
Epoch 20/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7379
Epoch 21/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7391
Epoch 22/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7383
Epoch 23/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7405
Epoch 24/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7399
Epoch 25/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7392
Epoch 26/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7411
Epoch 27/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7414
Epoch 28/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7387
Epoch 29/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7400
Epoch 30/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7410
Epoch 31/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7397
Epoch 32/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7405
Epoch 33/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7399
Epoch 34/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7400
Epoch 35/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7402
Epoch 36/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7392
Epoch 37/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7401
Epoch 38/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7395
Epoch 39/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7400
Epoch 40/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7402
Epoch 41/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7394
Epoch 42/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7405
Epoch 43/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7403
Epoch 44/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7406
Epoch 45/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7415
Epoch 46/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7409
Epoch 47/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7404
Epoch 48/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7413
Epoch 49/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7400
Epoch 50/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7411
Epoch 51/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7400
Epoch 52/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7384
Epoch 53/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7400
Epoch 54/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7407
Epoch 55/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7403
Epoch 56/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7404
Epoch 57/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7405
Epoch 58/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7406
Epoch 59/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7408
Epoch 60/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7405
Epoch 61/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7406
Epoch 62/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7407
Epoch 63/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7402
Epoch 64/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5333 - accuracy: 0.7404
Epoch 65/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5328 - accuracy: 0.7407
Epoch 66/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5327 - accuracy: 0.7407
Epoch 67/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5321 - accuracy: 0.7392
Epoch 68/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7410
Epoch 69/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7418
Epoch 70/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7407
Epoch 71/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7407
Epoch 72/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7404
Epoch 73/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7418
Epoch 74/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7415
Epoch 75/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7422

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [62]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
# Now we can evaluate the model by using the .evaluate() function. This function shows the performance of the model.
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
# Here we use a print command to print a f' string 
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5569 - accuracy: 0.7294 - 281ms/epoch - 1ms/step
Loss: 0.5569039583206177, Accuracy: 0.7294460535049438

In [61]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
# Now we can evaluate the model by using the .evaluate() function. This function shows the performance of the model.
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
# Here we use a print command to print a f' string 
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 0.0000e+00 - accuracy: 0.4708 - 265ms/epoch - 990us/step
Loss: 0.0, Accuracy: 0.4707871675491333

In [60]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
# Now we can evaluate the model by using the .evaluate() function. This function shows the performance of the model.
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
# Here we use a print command to print a f' string 
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 0.6082 - accuracy: 0.7306 - 300ms/epoch - 1ms/step
Loss: 0.6081980466842651, Accuracy: 0.7306122183799744

### Step 3: Save each of your alternative models as an HDF5 file.

In [54]:
# Set the file path for the first alternative model
# Here we name the model AlphabetSoup_A1.h5 and give it the variable name file_path.
file_path = 'AlphabetSoup_A1.h5'

# Export your model to a HDF5 file
# Here we use the save() function to save the model to the file path name we preciously determined. This way we can pass the model to a freind or
# colleague.
nn_A1.save(file_path)

In [55]:
# Set the file path for the second alternative model
# Here we name the model AlphabetSoup_A2.h5 and give it the variable name file_path.
file_path = 'AlphabetSoup_A2.h5'

# Export your model to a HDF5 file
# Here we use the save() function to save the model to the file path name we preciously determined. This way we can pass the model to a freind or
# colleague.
nn_A2.save(file_path)